# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ndTF4ptXVTksSPES4eTVUNfkEx9mcRo
"""

from google.colab import drive
drive.mount('/content/drive')

import sys
!git clone https://github.com/cofe-ai/CofeNet.git
sys.path.insert(0, '/content/CofeNet')

# Commented out IPython magic to ensure Python compatibility.
# %cd CofeNet
!pip install -r requirements.txt

!python run_train.py